import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import { Providers } from '@/redux/provider'
import Modal from '@/components/Modal'
import { Flowbite } from 'flowbite-react';
import theme from '@/components/theme'
import Alert from '@/components/Alert'
import "aos/dist/aos.css";
import { AOSInit } from '@/components/Aos'
import './page.module.css'

const inter = Inter({ subsets: ['latin'] })
declare global {
  interface Window {
    IMP: any
    daum: any
  }
}
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AOSInit />
        <Flowbite theme={{ theme }}>
          <Providers>
            {children}
            <Modal />
            <Alert />
          </Providers>
        </Flowbite>
      </body>
    </html>
  )
}
